name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_SERVER }}
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PW }}
    
    - name: Build and push Docker image (ARM64)
      uses: docker/build-push-action@v5
      with:
        platforms: linux/arm64
        push: true
        tags: cr.slackersoftware.com/epoch:latest